//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOpis")]
    public interface IOpis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpis/dajOpis", ReplyAction="http://tempuri.org/IOpis/dajOpisResponse")]
        string dajOpis(string nazwisko, string imie, int iii);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpis/dajOpis", ReplyAction="http://tempuri.org/IOpis/dajOpisResponse")]
        System.Threading.Tasks.Task<string> dajOpisAsync(string nazwisko, string imie, int iii);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOpisChannel : WcfServiceClient.ServiceReference1.IOpis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpisClient : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.IOpis>, WcfServiceClient.ServiceReference1.IOpis {
        
        public OpisClient() {
        }
        
        public OpisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string dajOpis(string nazwisko, string imie, int iii) {
            return base.Channel.dajOpis(nazwisko, imie, iii);
        }
        
        public System.Threading.Tasks.Task<string> dajOpisAsync(string nazwisko, string imie, int iii) {
            return base.Channel.dajOpisAsync(nazwisko, imie, iii);
        }
    }
}
