//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IOWSerwis")]
    public interface IOWSerwis {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOWSerwis/Funkcja1")]
        void Funkcja1(string s1);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOWSerwis/Funkcja1")]
        System.Threading.Tasks.Task Funkcja1Async(string s1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOWSerwis/Funkcja2", ReplyAction="http://tempuri.org/IOWSerwis/Funkcja2Response")]
        void Funkcja2(string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOWSerwis/Funkcja2", ReplyAction="http://tempuri.org/IOWSerwis/Funkcja2Response")]
        System.Threading.Tasks.Task Funkcja2Async(string s2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOWSerwisChannel : WcfServiceClient.ServiceReference2.IOWSerwis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OWSerwisClient : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference2.IOWSerwis>, WcfServiceClient.ServiceReference2.IOWSerwis {
        
        public OWSerwisClient() {
        }
        
        public OWSerwisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OWSerwisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OWSerwisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OWSerwisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Funkcja1(string s1) {
            base.Channel.Funkcja1(s1);
        }
        
        public System.Threading.Tasks.Task Funkcja1Async(string s1) {
            return base.Channel.Funkcja1Async(s1);
        }
        
        public void Funkcja2(string s2) {
            base.Channel.Funkcja2(s2);
        }
        
        public System.Threading.Tasks.Task Funkcja2Async(string s2) {
            return base.Channel.Funkcja2Async(s2);
        }
    }
}
