//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Isrv111")]
    public interface Isrv111 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isrv111/proc111", ReplyAction="http://tempuri.org/Isrv111/proc111Response")]
        long proc111(string s, int i, double d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isrv111/proc111", ReplyAction="http://tempuri.org/Isrv111/proc111Response")]
        System.Threading.Tasks.Task<long> proc111Async(string s, int i, double d);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Isrv111Channel : WcfServiceClient.ServiceReference2.Isrv111, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Isrv111Client : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference2.Isrv111>, WcfServiceClient.ServiceReference2.Isrv111 {
        
        public Isrv111Client() {
        }
        
        public Isrv111Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Isrv111Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Isrv111Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Isrv111Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long proc111(string s, int i, double d) {
            return base.Channel.proc111(s, i, d);
        }
        
        public System.Threading.Tasks.Task<long> proc111Async(string s, int i, double d) {
            return base.Channel.proc111Async(s, i, d);
        }
    }
}
